### PR TITLE
WIP - testing auto-upgrades

### PR DESCRIPTION
**Pull request by kyleclark171**
WIP

### CODE REVIEW

**Comment by jaycenhorton** [comment]
Bump package versions

**Comment by kyleclark171** [comment]
Bump package versions

**Comment by kyleclark171** [comment]
Bump package versions

**Comment by kyleclark171** [comment]
Bump package versions

**Comment by kyleclark171** [comment]
Bump package versions

**Comment by kyleclark171** [comment]
Bump package versions

**Comment by kyleclark171** [comment]
Bump package versions

**Review by kyleclark171 — COMMENTED** [review]
Bump package versions

**Pull request merged**
